package com.app.errors.utils;

//public class ExceptionUtil {
//	
//	/**
//	{
//	    "type": "about:blank",
//	    "title": "Not Found",
//	    "status": 404,
//	    "detail": "Error interno al realizar la operacion solicitada.",
//	    "instance": "/user/test"
//	}
//	 */
//
//	throw new ResponseStatusException(HttpStatus.NOT_FOUND, ErrorMessages.ERROR_MESSAGE__GeneralError, e);
//
//}
